# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ebb42aad973cec5fd4734ec5952c53e531df3829ef3aed71d9b9b2aa8ecdd0727e966a50c57bd999d12d377778161f6ba2d621ef5819fa2fb27fa2dd410506d

test:
  secret_key_base: 0686ff86a511a6f17f6b91c4a1f5bab7309ee4d57f0b910fd4ad4491c5ca5afb4bcd08c04f34b7fe41fe6c7f7ba0844f5faf7f5734cc69490d607ee28af0e9f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
